spring:
  profiles:
    active: dev
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawl
    username: root
    password: 1234
  jpa:
    habinate:
      ddl-auto: create
    show_sql: true